config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'dash_board/admin'
  get 'dash_board/customer'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'policies/display'
  get 'policies/policy_email'
  get 'policies/maturing'
  get 'companies/company_show'
  get 'sessions/new'
  root 'welcome#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'user/policies/new', to: 'policies#create'

  resources  :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  scope '/user' do
    resources :companies, :policytypes, :comments, :policies
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_many :policytype, dependent: :destroy
  has_many :policy, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  def index
    if logged_in?
      @companies = Company.all
    else
      redirect_to login_path
    end
  end

  def company_show
    if logged_in?
      @company = Company.find_by_id(params[:id])
    else
      redirect_to login_path
    end
  end

  def show; end

  def new
    if logged_in?
      @company = Company.new
      @user = current_user
    else
      redirect_to login_path
    end
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render 'new'
    end
  end

  def edit
    if logged_in?
      @company = Company.find(params[:id])
      @user = current_user
    else
      redirect_to login_path
    end
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companies_path
      flash[:success] = 'Company updated'
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @pol_d = Policy.where(company_id: @company.id)
    @pol_d.each do |i|
      i.destroy
    end
    @company.destroy
    redirect_to companies_path
    flash[:success] = 'Company Deleted!'
  end

  private

  def company_params
    params.require(:company).permit(:name, :description)
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @company, local: true) do |f| %>
			<%= render 'shared/company_errors' %>
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			<%= f.label :description %>
			<%= f.text_area :description, :cols => "10", :rows => "5", class: 'form-control' %>          
			<%= f.submit "Submit", class: "btn btn-primary custom_btn_small" %>
		<% end %>
	</div>
</div>

app/views/companies/companyShow.html.erb
<div class="container">
  <%= link_to "Back", companies_path,:class => "btn btn-primary custom_btn_small" %>
</div>
<% @plan=Policytype.where(:company_id => @company.id) %>
<% if @plan.count!=0 %>
  <div class="container">
    <h1 >All the plans of the company: <%= @company.name %> </h1>
    <% @plan.each do |i| %>
      <div class="container show-box">
        <h2><%=i.name%></h2>
        <p><strong>Description:</strong> <%=i.description%> </p><br>
        <p><strong>Duration:</strong> <%=i.duration%> years <br></p>
        <p><strong>Insured Amount:</strong> <%=i.sum_insured%> INR <br></p>
        <p><strong>Premium Amount:</strong> <%=i.premium_amt%> INR<br></p>
        <td> <%= link_to "Buy", new_policy_path(:company_id => i.company_id,:policytype_id => i.id),:class => "btn btn-primary custom_btn_small" %><td>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container">
    <h1>There are no plans of the company: <%= @company.name %> </h1>
  </div>
<% end %>

app/views/companies/company_show.html.erb
<div class="container">
  <%= link_to "Back", companies_path,:class => "btn btn-primary custom_btn_small" %>
</div>
<% @plan=Policytype.where(:company_id => @company.id) %>
<% if @plan.count!=0 %>
  <div class="container">
    <h1 >All the plans of the company: <%= @company.name %> </h1>
    <% @plan.each do |i| %>
      <div class="container show-box">
        <h2><%=i.name%></h2>
        <p><strong>Description:</strong> <%=i.description%> </p><br>
        <p><strong>Duration:</strong> <%=i.duration%> years <br></p>
        <p><strong>Insured Amount:</strong> <%=i.sum_insured%> INR <br></p>
        <p><strong>Premium Amount:</strong> <%=i.premium_amt%> INR<br></p>
        <td> <%= link_to "Buy", new_policy_path(:company_id => i.company_id,:policytype_id => i.id),:class => "btn btn-primary custom_btn_small" %><td>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container">
    <h1>There are no plans of the company: <%= @company.name %> </h1>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>
<% @user = current_user %>
<%= render "form" %>

app/views/companies/index.html.erb
<% @user = current_user %>
<% if(@companies.count!=0) %>
  <div class="container" >
    <h1>Companies</h1>
    <p class="text-style">This list displays all the available companies. 
      This list is only for viewing, to select a company and buy a policy from a specific company , 
    please visit <strong>Policy --> Add new policy</strong> </p><br><br>            
    <table class="table table-hover table-responsive">
      <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
        <% @companies.each do |i| %>
        <tr>
          <td><%=i.name%></td>
          <td><%=i.description %></td>
          <td><%= link_to "Plans", companies_company_show_path(:id => i.id), :class => "btn btn-primary custom_btn_small" %></td>
          <% if @user.admin? %>
            <td><%= link_to "Edit", edit_company_path(i), :class => "btn btn-primary custom_btn_small" %></td>
            <td><%= link_to 'Destroy', company_path(i),
                method: :delete,
                data: { confirm: 'Are you sure?' } , :class => "btn btn-primary custom_btn_small"%></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="container" >
    <h2>No companies available</h2>
    <p class="text-style">Please come back later</p><br><br>            
  </div>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>
<% @user = current_user %>
<%= render "form" %>