config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'dash_board/admin'
  get 'dash_board/customer'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'policies/display'
  get 'policies/policy_email'
  get 'policies/maturing'
  get 'companies/company_show'
  get 'sessions/new'
  root 'welcome#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'user/policies/new', to: 'policies#create'

  resources  :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  scope '/user' do
    resources :companies, :policytypes, :comments, :policies
  end
end

app/controllers/policytypes_controller.rb
# frozen_string_literal: true

class PolicytypesController < ApplicationController
  def index
    if logged_in?
      @policytypes = Policytype.includes(:company).all.reorder('Company_id')
      @allcompany = Company.all
    else
      redirect_to login_path
    end
  end

  def show; end

  def new
    if logged_in?
      @policytype = Policytype.new
      @allcompany = Company.all
    else
      redirect_to login_path
    end
  end

  def create
    @policytype = Policytype.new(policytype_params)
    if @policytype.save
      redirect_to policytypes_path
      flash[:success] = 'Plan created!'
    else
      render 'new'
    end
  end

  def edit
    if logged_in?
      @policytype = Policytype.includes(:company).find(params[:id])
      @user = current_user
      @allcompany = Company.all
    else
      redirect_to login_path
    end
  end

  def update
    @policytype = Policytype.includes(:company).find(params[:id])
    if @policytype.update(policytype_params)
      redirect_to policytypes_path
      flash[:success] = 'Edit Successful!'
    else
      render 'edit'
    end
  end

  def destroy
    @policytype = Policytype.includes(:company).find(params[:id])
    @policytype.destroy
    redirect_to policytypes_path
    flash[:success] = 'Plan deleted!'
  end

  private

  def policytype_params
    params.require(:policytype).permit(:name, :description, :company_id, :duration, :sum_insured, :premium_amt)
  end
end

app/helpers/policytypes_helper.rb
# frozen_string_literal: true

module PolicytypesHelper
end

app/views/policytypes/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<% @duration=[5,10,15,20,25,30,35,40,45,50] %>
		<%= form_with(model: @policytype, local: true) do |f| %>
			<%= render 'shared/plan_errors' %>
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			<%= f.label :description %>
			<%= f.text_area :description, :cols => "10", :rows => "5", class: 'form-control' %>  
			<%= f.label :company_id %>
			<%= f.select :company_id, @allcompany.map{|i| [i.name,i.id]}, {}, class: 'form-control' %>
			<%= f.label :duration %>
			<%= f.select :duration, @duration, {}, class: 'form-control' %>
			<%= f.label :sum_insured %>
			<%= f.text_field :sum_insured, placeholder: 'in INR', class: 'form-control' %>
			<%= f.label :premium_amt %>
			<%= f.text_field :premium_amt, placeholder: 'in INR', class: 'form-control' %>
			<%= f.submit "Submit", class: "btn btn-primary custom_btn_small" %>
		<% end %>
	</div>
</div>



app/views/policytypes/edit.html.erb
<% @allcompany= Company.all %>
<h1> Edit Plan </h1>
<% @user = current_user %>
<%= render "form" %>

app/views/policytypes/index.html.erb
<% @user = current_user %>
<% if (@policytypes.count!=0) %>

  <div class="container" >
    <h2> Plans </h2>
    <p class="text-style"> All the available plans of listed companies </p>            
    <table class="table table-hover table-responsive">
      <thead class="thead-inverse">
        <tr>
          <th>Company Name</th>
          <th>Policy Type</th>
          <th>Description</th>
          <th>Duration</th>
          <th>Insurance Amount</th>
          <th>Premium Amount</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @policytypes.each do |i| %>
          <tr>
            <% @company= Company.find(i.company_id) %>
            <td><%= @company.name %></td>
            <td><%= i.name %></td>
            <td><%= i.description %></td>
            <td><%= i.duration %></td>
            <td><%= i.sum_insured %></td>
            <td><%= i.premium_amt %></td>
            <td> <%= link_to "Buy", new_policy_path(:company_id => i.company_id,:policytype_id => i.id),:class => "btn btn-primary custom_btn_small" %><td>
            <% if @user.admin? %>
              <td><%= link_to "Edit", edit_policytype_path(i), :class => "btn btn-primary custom_btn_small" %></td>
              <td><%= link_to 'Destroy', policytype_path(i),
              method: :delete,
              data: { confirm: 'Are you sure?' } , :class => "btn btn-primary custom_btn_small"%></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="container" >
    <h2> No Plans Available. </h2>
    <p> Please come back later. </p><br><br>            
  </div>
<% end %>

app/views/policytypes/new.html.erb
<% @allcompany= Company.all %>
<% if (@allcompany.count!=0)%>
  <h1> Add New Plan </h1>
  <% @user = current_user %>
  <%= render "form" %>
<% else %>
  <h1> No companies available!! Please add a company to continue adding a plan </h1>
<% end %>