config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'dash_board/admin'
  get 'dash_board/customer'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'policies/display'
  get 'policies/policy_email'
  get 'policies/maturing'
  get 'companies/company_show'
  get 'sessions/new'
  root 'welcome#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'user/policies/new', to: 'policies#create'

  resources  :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  scope '/user' do
    resources :companies, :policytypes, :comments, :policies
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "insurance manager", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
        id="bs-example-navbar-collapse-1">
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Dashboard", dash_board_admin_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Users <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Add New User", signup_path %></li>            
                <li><%= link_to "View All Users", users_path %></li>            
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Dashboard", dash_board_customer_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Policies <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add New Policy", new_policy_path %></li> 
              <% if current_user.admin? %>
                <li><%= link_to "View All Policies", policies_path %></li>
                <li><%= link_to "Maturing Policies", policies_maturing_path %></li>
              <% else %>
                <li><%= link_to "View My Policies", policies_path %></li>
              <% end %>
            </ul>
          </li>
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Companies <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View all Companies", companies_path %></li>                          
              <% if current_user.admin? %>
                <li><%= link_to "Add New Company", new_company_path %></li>
              <% end %>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Plans <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View all Plans", policytypes_path %></li>                         
              <% if current_user.admin? %>
                <li><%= link_to "Add New Plan", new_policytype_path %></li>
              <% end %>
            </ul>
          </li>
            
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Details", edit_user_path(current_user) %></li>                          
              <li><%= link_to "Home", root_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsurancePolicyManager</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>