config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'dash_board/admin'
  get 'dash_board/customer'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'policies/display'
  get 'policies/policy_email'
  get 'policies/maturing'
  get 'companies/company_show'
  get 'sessions/new'
  root 'welcome#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'user/policies/new', to: 'policies#create'

  resources  :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  scope '/user' do
    resources :companies, :policytypes, :comments, :policies
  end
end

app/models/policy.rb
# frozen_string_literal: true

class Policy < ApplicationRecord
  belongs_to :user
  belongs_to :policytype
  belongs_to :company

  has_many_attached :documents
  has_many :comments, dependent: :destroy

  validates :policy_type, presence: true
  validates :sum_insured, presence: true
  validates :premium_amt, presence: true
  validates :commission, presence: true
  validates :purchase_date, presence: true
  validates :mature_date, presence: true
  validates :user_id, presence: true
  validates :company_id, presence: true
  validates :policytype_id, presence: true
end

app/models/policytype.rb
# frozen_string_literal: true

class Policytype < ApplicationRecord
  belongs_to :company
  has_many :policy, dependent: :destroy
  validates :name, presence: true
  validates :company_id, presence: true
  validates :duration, presence: true
  validates :premium_amt, presence: true, numericality: true
  validates :sum_insured, presence: true, numericality: true
end

app/controllers/policies_controller.rb
# frozen_string_literal: true

class PoliciesController < ApplicationController
  def index
    if logged_in?
      @policies = Policy.includes(:user, policytype: [:company]).all
      @user = current_user
    else
      redirect_to login_path
    end
  end

  def new
    if logged_in?
      @usr = User.find_by(id: current_user.id)
      @policy = Policy.new
      @c_id = params[:company_id]
      @p_id = params[:policytype_id]
      @u_id = params[:user_id]
      @pol_id = params[:id]
      @user = current_user
      redirect_to policies_select_company_path if @c_id.nil?
    else
      redirect_to login_path
    end
  end

  def create
    @policy = Policy.new(policy_params)
    if @policy.save
      redirect_to policies_path
      flash[:success] = 'Policy created!'
    else
      redirect_back fallback_location: { action: 'create' }
      flash[:danger] = 'Fill all compulsory fields! (User and sum insured should not be empty)'
    end
  end

  def show; end

  def display
    if logged_in?
      @policy = Policy.includes(:user, policytype: [:company]).find_by_id(params[:id])
    else
      redirect_to login_path
    end
  end

  def maturing
    if logged_in?
      @policy = Policy.includes(:user, policytype: [:company]).find_by_id(params[:id])
      @policies = Policy.all
      @user = current_user
    else
      redirect_to login_path
    end
  end

  def policy_email
    PolicyMailer.policy_email.deliver_now
    redirect_back fallback_location: { action: 'display' }
    flash[:success] = 'Mail sent successfully'
  end

  def select_company
    if logged_in?
      @allcompany = Company.all
    else
      redirect_to login_path
    end
  end

  def select_plan
    if logged_in?
      @c_id = params[:company_id]
    else
      redirect_to login_path
    end
  end

  def edit
    if logged_in?
      @policy = Policy.includes(:user, policytype: [:company]).find(params[:id])
      @user = current_user
    else
      redirect_to login_path
    end
  end

  def update
    @policy = Policy.includes(:user, policytype: [:company]).find(params[:id])
    if @policy.update(policy_params)
      redirect_to policies_path
      flash[:success] = 'Policy updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @policy = Policy.includes(:user, policytype: [:company]).find(params[:id])
    @policy.destroy
    redirect_to policies_path
    flash[:success] = 'Policy deleted!'
  end

  private

  def policy_params
    params.require(:policy).permit(:policy_type, :description, :sum_insured, :premium_amt, :commission, :purchase_date,
                                   :mature_date, :user_id, :company_id, :policytype_id, documents: [])
  end
end

app/helpers/policies_helper.rb
# frozen_string_literal: true

module PoliciesHelper
end

app/views/policies/display.html.erb
<div class="container">
  <%= link_to "Mail", policies_policy_email_path , :class => "btn btn-primary custom_btn_small" %>
</div> <br>
<% @user = current_user %>
<% @usr=User.find(@policy.user_id) %>
<% @com = Company.find(@policy.company_id) %>
<% @plan = Policytype.find(@policy.policytype_id) %>
<div class="container show-box">
  <p><strong> Holder's Name : </strong><%= @usr.name %></p><br>
  <p><strong> Company Name : </strong><%= @com.name %></p><br>
  <p><strong> policy Type : </strong><%= @policy.policy_type %></p><br>
  <p><strong> Description : </strong><%= @policy.description %></p><br>
  <p><strong> Sum insured : </strong><%= @policy.sum_insured %></p><br>
  <p><strong> Premium amount : </strong><%= @policy.premium_amt %></p><br>
  <p><strong> Commission : </strong><%= @policy.commission %></p><br>
  <p><strong> Purchase date : </strong><%= @policy.purchase_date %></p><br>
  <p><strong> Mature date : </strong><%= @policy.mature_date %></p><br><br>
  
  <% if @policy.documents.attached? %>
    <p><strong> Documents : </strong></p>
    <% @policy.documents.each do |doc| %>
      <%= link_to doc.filename, rails_blob_path(doc), :class => "btn btn-primary custom_btn_small" %>
    <% end %>
  <% else %>
    <p><strong> Documents :</strong> No documents attached</p>
  <% end %>
  <br><br>
 
  <% if @user.admin? %>
    <%= link_to "Edit", edit_policy_path(@policy), :class => "btn btn-primary custom_btn_small" %> 
    <%= link_to 'Delete', policy_path(@policy),
    method: :delete,
    data: { confirm: 'Are you sure?' } , :class => "btn btn-primary custom_btn_small" %>
  <% else %>
    <%= link_to "Upload Documents", edit_policy_path(@policy) ,:class => "btn btn-primary custom_btn_small" %>
  <% end %>
</div>

app/views/policies/edit.html.erb
<% @usr = User.find(@policy.user_id) %>
<div class="container" style="max-width: 50%; align-self: center;">
  <h3 style="text-align: center;"> Edit Policy </h3><br>
  <h3> Holder: <%= @usr.name %> </h3><br>
  <%= form_with(model: @policy, local: true) do |f| %>
    <%= render 'shared/policy_errors' %>
    
    <%= f.hidden_field :user_id, :value => @policy.user_id , :class => "form-control", :readonly => true %>
    <% if @user.admin? %>
      <%= f.label :description, "Description" %>  
      <%= f.text_area :description, :cols => "10", :rows => "5", :class => "form-control" %>
      <%= f.label :sum_insured, "Sum Insured" %>
      <%= f.text_field :sum_insured, :value => @policy.sum_insured, :class => "form-control", :readonly => true %>
      <%= f.label :premium_amt, "Premium Amount" %>
      <%= f.text_field :premium_amt, :value => @policy.premium_amt, :class => "form-control", :readonly => true %>
      <%= f.label :commission, "Commission" %>
      <%= f.text_field :commission,:value => @policy.commission, :class => "form-control", :readonly => true %>
      <%= f.label :purchase_date, "Purchase Date" %>
      <%= f.text_field :purchase_date, :value => @policy.purchase_date , :class => "form-control", :readonly => true %>
      <%= f.label :mature_date, "Mature Date" %>
      <%= f.date_field :mature_date, :value => @policy.mature_date , :class => "form-control" %>
      <%= f.hidden_field :company_id, :value => @policy.company_id, :class => "form-control", :readonly => true %>
      <%= f.hidden_field :policytype_id, :value => @policy.policytype_id, :class => "form-control", :readonly => true %>
      <%= f.label :policy_type, "Policy Type" %>
      <%= f.text_field :policy_type, :value => @policy.policy_type, :class => "form-control", :readonly => true %>
    <% end %>

    <% if @policy.documents.attached? %>
      <% @policy.documents.each do |doc| %>
        <%= link_to doc.filename, rails_blob_path(doc), :class => "btn btn-primary custom_btn_small" %>
      <% end %>
    <% end %> 
    <br> <br>
    <%= f.label :documents, "Documents" %>
    <%= f.file_field :documents, multiple: true, :class => "form-control" %>

    <%= f.submit "Edit Policy", :class => "btn btn-primary custom_btn_small" %>
  <% end %>
</div>


app/views/policies/index.html.erb
<% @policies= Policy.all %>
<% if @user.admin? %>
<% @pol = @policies %>
<% else %>
<% @pol=Policy.where(:user_id => @user.id) %>
<% end %>
<% if(@pol.count!=0) %>
  <div class="container" >
    <h2>Policies</h2>
    <p class="text-style">This list displays all the available policies bought by user. 
    This list is only for viewing, to buy a policy from a specific company, 
    Please visit <strong>Policy --> Add new policy</strong> </p> <br><br>                 
    <table class="table table-responsive table-hover">
      <thead>
        <tr>
          <th>Holders Name</th>
          <th>Company Name</th>
          <th>Policy Type</th>
          <th>Sum Insured</th>
          <th>Premium Amount</th>
          <th>Commission</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @pol.each do |i| %>
          <% @usr=User.find(i.user_id) %>
          <% @company=Company.find(i.company_id) %>
          <% @policytype=Policytype.find(i.policytype_id) %>
          <tr>
            <% @pol_id = i.id %>
            <% @u_id = current_user.id %>
            <td><%= @usr.name %></td>
            <td><%= @company.name %></td>
            <td><%= i.policy_type %></td>
            <td><%= i.sum_insured %></td>
            <td><%= i.premium_amt %></td>
            <td><%= i.commission %></td>
            <td><%= link_to "Policy Details", policies_display_path(:id => i.id),:class => "btn btn-primary" %></td>
            <td><%= link_to "Comments", comments_path(:id => i.id),:class => "btn btn-primary" %></td> 
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="container" >
    <h3> Policies </h3>
    <p> No policies to display, 
    Please visit <strong>Policy --> Add new policy</strong></p><br><br>                 
  </div>
<% end %>

app/views/policies/maturing.html.erb
<% @policies= Policy.all %>
<% @mat_pol = Policy.where('mature_date <= ?', Date.current + 15.day) %>
<% if(@mat_pol.count == 0) %>
	<div class="container" >
	
	<p> No policies are about to expire recently</p><br><br>                 
	</div>
<% else %>

	<div class="container" >
		<h2>Policies</h2>
		<p class="text-style">This list displays all the available policies that are going to expire 
		within next 15 days. </p> <br><br> 
									
		<table class="table table-responsive table-hover">
			<thead>
				<tr>
					<th>Holders Name</th>
					<th>Company Name</th>
					<th>Policy Type</th>
					<th>Sum Insured</th>
					<th>Premium Amount</th>
					<th>Commission</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @mat_pol.each do |i| %>
					<% @p_usr=User.find(i.user_id) %>
					<% @company=Company.find(i.company_id) %>
					<% @policytype=Policytype.find(i.policytype_id) %>
					<tr>
						<% @pol_id = i.id%>
						<% @u_id = current_user.id %>
						<td><%= @p_usr.name %></td>
						<td><%= @company.name %></td>
						<td><%= i.policy_type %></td>
						<td><%= i.sum_insured %></td>
						<td><%= i.premium_amt %></td>
						<td><%= i.commission %></td>
						<td><%= link_to "Policy Details", policies_display_path(:id => i.id),:class => "btn btn-primary" %></td>
						<td><%= link_to "comments", comments_path(:id => i.id),:class => "btn btn-primary" %></td> 
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% end %>




            

app/views/policies/new.html.erb
<% @c_id %>
<% @p_id %>
<% @company= Company.find(@c_id) %>
<% @plan = Policytype.find(@p_id) %>

<p id="pol_duration" class="hidden"><%= @plan.duration %></p>
<p id="pol_ins_amt" class="hidden"><%= @plan.sum_insured %></p>
<h1 class="form-info">Add new policy</h1>
<div class="container box-form">
  <%= form_with(model: @policy, url: new_policy_path, local: true) do |f| %>
    <%= render 'shared/policy_errors' %>
    <% @date= Date.today() + @plan.duration.year %>

    <% if @user.admin? %>
      <%= f.label :user_id, "User" %>
      <%= f.collection_select :user_id, User.all, :id, :name, {include_blank: "Select User"} %>
    <% else %>
      <%= f.hidden_field :user_id, :value => @user.id, :class => "form-control", :readonly => true %>
    <% end %>
     
    <%= f.label :policy_type, "Policy Type" %>
    <%= f.text_field :policy_type, :value => @plan.name, :class => "form-control", :readonly => true %>
    <%= f.hidden_field :description, :value => @plan.description, :class => "form-control", :readonly => true %>
    <%= f.label :sum_insured, "Sum Insured" %>
    <%= f.text_field :sum_insured, id: 'sum_ins' , :value => @plan.sum_insured,  min: '1000', step: '15000', max: @plan.sum_insured , :class => "form-control" %>
    <%= f.label :premium_amt, "Premium Amount" %>
    <%= f.text_field :premium_amt, id: 'prem_amt', :class => "form-control", :readonly => true %>
    <%= f.label :commission, "Commission" %>
    <%= f.text_field :commission, id: 'com', :class => "form-control", :readonly => true %>
    <%= f.label :purchase_date, "Purchase Date" %>
    <%= f.text_field :purchase_date, :value => Date.today , :class => "form-control", :readonly => true %>
    <%= f.label :mature_date, "Mature Date" %>
    <%= f.date_field :mature_date, :value => @date , :class => "form-control", :readonly => true %>
    <%= f.hidden_field :company_id, :value => @c_id, :class => "form-control", :readonly => true %>
    <%= f.hidden_field :policytype_id, :value => @p_id, :class => "form-control", :readonly => true %>


    <%= f.label :documents, "Documents (optional)" %>
    <%= f.file_field :documents, multiple: true, :class => "form-control" %>

    <%= f.submit "Create Policy", :class => "btn btn-primary custom_btn_small" %>
  <% end %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    v = $('#pol_ins_amt').text();
    dur = $('#pol_duration').text();
    if(dur!=0)
    var total = parseInt(v/dur);
    var com = parseInt(0.2 * total);
    $("#prem_amt").val(total);
    $("#com").val(com)

  });
  $("#sum_ins").change(function(){
    dur = $('#pol_duration').text();
    var price = Number($(this).val());
    if(dur!=0)
    var total = parseInt((price)/dur);
    var com = parseInt(0.2 * total);
    $("#prem_amt").val(total);
    $("#com").val(com)
  });

  function updatePrice(val)
  {
    $("#sum_ins").val(val);
    $("#sum_ins").trigger('change');
  }

</script>

app/views/policies/select_company.html.erb
<% if(@allcompany.count!=0) %>
  <div class="container">
    <h1 class="heading">  Step 1 :   Select a Company whose policy you want to buy </h1>
    <div class="rows">
      <% @allcompany.each do |i| %>
      <%= link_to policies_select_plan_path(:company_id => i.id) do %>
      <div class="col-md-5 company-type-box" >
        <h3> <%=i.name%> </h3>
        <br> Description: <%=i.description%> <br>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="container">
    <h1> No companies to display. Please come back later. </h1>  
  </div>
<% end %>

app/views/policies/select_plan.html.erb
<% @c_id %>
<% @plans=Policytype.where(:company_id => @c_id) %>
  <% if @plans.count!=0 %>
    <div class="container">
      <h1> Step 2 :   Select a plan </h1>
      <div class="rows">
        <% @plans.each do |i| %> 
        <%= link_to new_policy_path(:company_id => @c_id,:policytype_id => i.id) do %>
        <div class="col-md-5 policy-type-box" >
          <h2><%=i.name%></h2>
          <br><strong>Description:</strong> <%=i.description%> <br>
          <br><strong>Duration:</strong> <%=i.duration%> <br>
          <br><strong>Insured Amount:</strong> <%=i.sum_insured%> INR <br>
          <br><strong>Premium Amount:</strong> <%=i.premium_amt%> INR<br>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
    <% @c= Company.find(@c_id) %>
    <div class="container">
      <h1> No plans for the chosen company : <%= @c.name %> <br> Choose a different company</h1>      
      <%= link_to "Go back", policies_select_company_path,:class => "btn btn-primary custom_btn_small" %>
    </div>
  <% end %>

app/views/policies/show.html.erb
<div>
	<%= @policy.images.each do |image| %>
		<%= image %>
	<% end %>
</div>